### ISSUE TITLE
1.19.2 BUG ?

### ISSUE THREAD

**Issue by comonier** [EwyBoy/FPS-Monitor#10]
![image](https://user-images.githubusercontent.com/19571541/201149911-5dd5561c-e07a-435c-87e0-71e6bfb65340.png)
![image](https://user-images.githubusercontent.com/19571541/201150025-b45e4837-9d9d-47d5-9389-34afec80b28f.png)

**Comment by comonier** [comment]
FIRST TRY -
1 - REMOVE FILES AND FOLDERS INSIDE MODS FOLDER
![image](https://user-images.githubusercontent.com/19571541/201150713-2b60b9e3-0eaa-49dd-a85a-c4586ca2f891.png)


it says i have that:
![image](https://user-images.githubusercontent.com/19571541/201150912-01a0f009-8fd4-4018-a737-f68d679c5f5d.png)


and the issue stills on [the problem was not fixed by that actions] 
![image](https://user-images.githubusercontent.com/19571541/201151026-14c8c5ce-3d8c-4f05-a2bb-030735b1f481.png)

what should i do now ?

**Comment by comonier** [comment]
SECOND TRY

create a folder inside mods folder named alone and moved all other mods inside that
![image](https://user-images.githubusercontent.com/19571541/201151563-d5c44559-f23f-4969-a78f-099e7d39e0b1.png)

opened minecraft with only 1 mod [but it keep saying have 3 - i dont know why]
![image](https://user-images.githubusercontent.com/19571541/201151719-3f63bc5f-8451-49e0-8dca-81cb8a5fb5bf.png)

but it fix the problem i guess
![image](https://user-images.githubusercontent.com/19571541/201151992-4a09e3d4-f1cf-4f78-a43e-57835d8853df.png)


what mod is it incompatible with?

**Comment by comonier** [comment]
TRY Nº 3 )

Trying to Load FPS Monitor with Compass mod.
![image](https://user-images.githubusercontent.com/19571541/201152373-9aeca4ff-2d2f-4a72-91af-26d376678017.png)
![image](https://user-images.githubusercontent.com/19571541/201152431-f1fbc9f4-be73-4d08-8896-1ebc7fee3bda.png)
![image](https://user-images.githubusercontent.com/19571541/201152516-47b95b7c-b820-4c99-ae45-7dd2bb35de03.png)

its it, found the issue - can you try to fix it ?

**Comment by comonier** [comment]
TRY Nº 4)

Trying to open minecraft with FPS Monitor and all others [ BUT NOT COMPASS MOD ]

7 is = 5 on true
![image](https://user-images.githubusercontent.com/19571541/201153021-722627bd-a6c1-4358-8b25-bc17f6f75bc3.png)
![image](https://user-images.githubusercontent.com/19571541/201153199-b354b5de-f83e-4b39-b8c0-9f306f9c42ff.png)
 - yes i have it all working - but not compass mod

**Comment by comonier** [comment]
have openned a ticket on advanced compass mod github linking that ticket here.
https://www.curseforge.com/minecraft/mc-mods/advanced-compass/issues/46

**Comment by EwyBoy** [comment]
Okey, one thing first before I try fix it.
Where did you download the mods from?

**Comment by comonier** [comment]
fps monitor 

> Okey, one thing first before I try fix it. Where did you download the mods from?

 https://www.curseforge.com/minecraft/mc-mods/fps-monitor
 https://www.curseforge.com/minecraft/mc-mods/advanced-compass
 
the bug only occurs when you put the co-compass mod along with the fps

**Comment by EwyBoy** [comment]
If you downloaded it from https://www.curseforge.com/minecraft/mc-mods/fps-monitor.
Why is the name of the jar file FPS-Monitor-Mod-Forge-1.19.2.jar?

**Comment by comonier** [comment]
> If you downloaded it from https://www.curseforge.com/minecraft/mc-mods/fps-monitor. Why is the name of the jar file FPS-Monitor-Mod-Forge-1.19.2.jar?

good question - i dont know why, but i got it.
the file name should to be FPS-Monitor-1.19.2-1.3.0.jar right ? (i just have done a new download now)
I really dont know why the name on the print is different from the file on curse site.
Probally the first time i did the download the name was like on the print.
But both files have the same size.
![image](https://user-images.githubusercontent.com/19571541/201500398-834da1d5-30ff-4c5c-8ce9-19867401932b.png)

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/201500426-5ed45404-9d2d-45b7-a0ca-04f3fe305f40.png)

**Comment by comonier** [comment]
probally i should renamed it ?

**Comment by comonier** [comment]
the most strange is, i am using that version on print and there is no bug [i am on other computer now]
i will check your version again when i get back to other computer to check if the file is corrupted.
like i said [new information] there is no bug on that computer i am using now.

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/201500482-d3c0248b-b74b-4b51-8ad0-ba0e22d48438.png)

**Comment by comonier** [comment]
monday i will get back to my house, [the computer i have related the bug] i will replace that files to check if is onlu the file from curse site is corrupted so we will keep the mistery ... from were i have downloaded the working version.... i will try to find it on chrome history

**Comment by comonier** [comment]
> If you downloaded it from https://www.curseforge.com/minecraft/mc-mods/fps-monitor. Why is the name of the jar file FPS-Monitor-Mod-Forge-1.19.2.jar?

**i found it**
https://www.9minecraft.net/fps-monitor-mod/

probally that version is working and curse site not ? 🤔

![image](https://user-images.githubusercontent.com/19571541/201500556-8b90a9dd-ecc1-4549-b9a8-9c0a766c14d7.png)

**Comment by EwyBoy** [comment]
Never ever download Minecraft mods from any other place outside https://www.curseforge.com/ or https://modrinth.com/
The Curseforge and modrinth is the only two official sites Minecraft modders upload their mods.

9Minecraft is a hacked website that steals peoples mods and add viruses to them so people download them and infect their PC's with viruses and malware. I suggest you do a full scan of your computer after having used mods from 9Minecraft.

Minecraft mods is something I spend a huge amount of time and energy on my free time and I don't appreciate people sealing my work to turn it into malware.

There is a chrome extension that helps you stay away from these sites you can download from here:
https://stopmodreposts.org/
The site contains more info on why mod sites like 9Minecraft is bad and why you should never download from it.

**Comment by EwyBoy** [comment]
Link to chrome extension: https://stopmodreposts.org/extension

**Comment by comonier** [comment]
> Link to chrome extension: https://stopmodreposts.org/extension

ty i add it, but why that version works and yours no ?
