### ISSUE TITLE
Update to 1.19.4?

### ISSUE THREAD

**Issue by Spursf** [EwyBoy/FPS-Monitor#14]
Will there be a version for 1.19.4 (fabric)?

**Comment by EwyBoy** [comment]
Scheduled for update tomorrow. Both Fabric & Forge.

**Comment by Spursf** [comment]
I made a pull request for the fabric version to be updated to 1.19.4.

**Comment by EwyBoy** [comment]
**Updated to 1.19.4**

- Fabric: https://legacy.curseforge.com/minecraft/mc-mods/fps-monitor/files/4515318
- Forge: https://legacy.curseforge.com/minecraft/mc-mods/fps-monitor/files/4515321
