### ISSUE TITLE
Upload to modrinth

### ISSUE THREAD

**Issue by MOTHmusic** [EwyBoy/FPS-Monitor#15]
Can you please upload this to modrinth as well? I get most of my mods there and it would be such a help

**Comment by EwyBoy** [comment]
Eventually, I have 36 mods on Curseforge and I can't manually just transfer all 36 of them.
Waiting for a tool a friend of mine is creating to automatically transfer the mods over from CurseForge to Modrinth.
No ETA

**Comment by alaestor** [comment]
It seems you've uploaded them to Modrinth. I think you can close this now.
