### ISSUE TITLE
1.3.0 fabric on modrinth only shows as 1.20

### ISSUE THREAD

**Issue by Aces-and-Jacks** [EwyBoy/FPS-Monitor#19]
1.3.0 fabric on GitHub only shows as 1.20 instead of 1.20-1.20.1. However on curs forge it shows as 1.20.1

**Comment by EwyBoy** [comment]
I don't quite understand the issue here?
Is there anything wrong?

**Comment by Aces-and-Jacks** [comment]
Well for launchers that detect the mod version it'd be helpful if it was marked as 1.20-1.20.1 instead of only working for 1.20

**Comment by Aces-and-Jacks** [comment]
the mod works fine tho

**Comment by EwyBoy** [comment]
What launcher is using GitHub to detect versions of my mod?
I have no official builds hosted on github.

**Comment by Aces-and-Jacks** [comment]
No I mean on curseforge and modrinth. 
<img width="1494" alt="Screen Shot 2023-07-20 at 12 54 00 PM" src="https://github.com/EwyBoy/FPS-Monitor/assets/106651342/dd8f19e8-24b5-4817-a147-40e1b319b7ac">
<img width="1494" alt="Screen Shot 2023-07-20 at 12 54 26 PM" src="https://github.com/EwyBoy/FPS-Monitor/assets/106651342/045828a6-c88f-4180-bdd1-604ff40ee823">

the supported game versions

**Comment by Aces-and-Jacks** [comment]
curseforge is fine. I was just referring to modrinth

**Comment by EwyBoy** [comment]
Ahh modrinth yes, you said github 😛
I can fix that

**Comment by Aces-and-Jacks** [comment]
oh. my mistake then

**Comment by EwyBoy** [comment]
Its fixed now!
Might take a minute or two to update 👍 
Thanks!
