### ISSUE TITLE
Question about Cloth Config

### ISSUE THREAD

**Issue by Chunk-de-Ra** [EwyBoy/FPS-Monitor#2]
How do I go about installing Cloth Config so that I can see the in-game settings menu you screenshotted? I installed the most recent 1.18.1 version (cloth-config-6.1.48-fabric), but it doesn't ever appear to load. Am I doing something wrong?

**Comment by EwyBoy** [comment]
Hmm, I am currently on vacation so hard for me to say or test it.
It was working for me with cloth-config 6.0.x but not sure with 6.1.x.
There is also a chance I have messed something up..
I will come back to this issue when I am home.

Thanks for the report

**Comment by EwyBoy** [comment]
Just tested it on 1.18.1 and everything seems to work just fine.
Make sure you got Mod Menu installed: https://www.curseforge.com/minecraft/mc-mods/modmenu

**Comment by Chunk-de-Ra** [comment]
Yep, that was my issue. Thank you so much!!

**Comment by EwyBoy** [comment]
Awesome, glad we sorted it out.
