### ISSUE TITLE
doesn't show up in mod menu

### ISSUE THREAD

**Issue by invisyarcticfox** [EwyBoy/FPS-Monitor#4]
![image](https://user-images.githubusercontent.com/68004605/158089253-22944455-c68e-4ada-ba60-b2a3e4f7d3e9.png)

¯\_(ツ)_/¯

**Comment by dragon3025** [comment]
I don't know if this is normal or not, but there's no configuration for it in the configuration folder.

**Comment by EwyBoy** [comment]
Mind filling out some extra information for me so I can easier debug this issue?

###### **Minecraft Version**
> Type here

###### Modloader Fabric / Forge
> Type here

###### **Modloader Version**
> Type here

###### **Mod Version**
> Type here

**Comment by Emperorpacify** [comment]
> ![image](https://user-images.githubusercontent.com/68004605/158089253-22944455-c68e-4ada-ba60-b2a3e4f7d3e9.png)
> 
> ¯_(ツ)_/¯

Doesnt work for me aswell idk why

**Comment by EwyBoy** [comment]
> > ![image](https://user-images.githubusercontent.com/68004605/158089253-22944455-c68e-4ada-ba60-b2a3e4f7d3e9.png)
> > ¯_(ツ)_/¯
> 
> Doesnt work for me aswell idk why

Can you send me the name of the jar file you have in you mods folder 📁

**Comment by Emperorpacify** [comment]
> > Doesnt work for me aswell idk why
> 
> Can you send me the name of the jar file you have in you mods folder 📁

FPS-Monitor-1.17.1-1.0.0.jar

**Comment by Emperorpacify** [comment]
> > > ![image](https://user-images.githubusercontent.com/68004605/158089253-22944455-c68e-4ada-ba60-b2a3e4f7d3e9.png)
> > > ¯_(ツ)_/¯
> > 
> > 
> > Doesnt work for me aswell idk why
> 
> Can you send me the name of the jar file you have in you mods folder 📁

FPS-Monitor-1.17.1-1.0.0.jar 
i downloaded it from the curseforge trying to use fabric

**Comment by EwyBoy** [comment]
> FPS-Monitor-1.17.1-1.0.0.jar

Interesting, there is literally no version ever releases under that build name.

Can you link me where you got the download from to that jar?

**Comment by Emperorpacify** [comment]
> > FPS-Monitor-1.17.1-1.0.0.jar
> 
> Interesting, there is literally no version ever releases under that build name.
> 
> Can you link me where you got the download from to that jar?

Welp I got it from this link the 1.17.1 Download File
 https://www.curseforge.com/minecraft/mc-mods/fps-monitor/files

**Comment by EwyBoy** [comment]
All files have a -fabric or a -forge at the end. Are you sure you have the right version?

**Comment by Emperorpacify** [comment]
> All files have a -fabric or a -forge at the end. Are you sure you have the right version?

I mean I'm pretty sure but do u have another file that i can download so i can use the mod if so please send link and tysm

**Comment by Emperorpacify** [comment]
> All files have a -fabric or a -forge at the end. Are you sure you have the right version?

Well that's weird, also i went back to the curseforge file where i downloaded it and it said -Fabric on it but when i download it, i get a file that has different name than the name said on the curseforge link ill send screenshot
![Screenshot (312)](https://user-images.githubusercontent.com/102956652/161522774-8ed92bdf-9efe-4504-93ff-4a2247404800.png)
s
![Screenshot (311)](https://user-images.githubusercontent.com/102956652/161522793-8af18ea8-59f4-472b-8666-aee38c903d15.png)

**Comment by EwyBoy** [comment]
Going to look into it once I get home.

**Comment by Emperorpacify** [comment]
> Going to look into it once I get home.

u home yet? sorry don't want to bother you but i just thought u forgot

**Comment by EwyBoy** [comment]
> > Going to look into it once I get home.
> 
> u home yet? sorry don't want to bother you but i just thought u forgot

Still at work, once I get home and make myself some dinner I will look at it.

**Comment by EwyBoy** [comment]
![image](https://user-images.githubusercontent.com/5883716/161590400-28428ddc-c1b1-4762-b316-557c7826fb69.png)
Have you tried installing https://www.curseforge.com/minecraft/mc-mods/fabric-api/ that most Fabric mods require to work?

**Comment by EwyBoy** [comment]
![image](https://user-images.githubusercontent.com/5883716/161605689-97a0fb2a-c04c-4c6a-a124-022864ba8c2a.png)
Released 6 new builds that should potentially fix all this 🤞🤞

**Comment by EwyBoy** [comment]
https://www.curseforge.com/minecraft/mc-mods/fps-monitor/files

**Comment by Emperorpacify** [comment]
> ![image](https://user-images.githubusercontent.com/5883716/161590400-28428ddc-c1b1-4762-b316-557c7826fb69.png)
> Have you tried installing https://www.curseforge.com/minecraft/mc-mods/fabric-api/ that most Fabric mods require to work?

Of course I have all of my fabric files downloaded

**Comment by Emperorpacify** [comment]
> ![image](https://user-images.githubusercontent.com/5883716/161605689-97a0fb2a-c04c-4c6a-a124-022864ba8c2a.png)
> Released 6 new builds that should potentially fix all this 🤞🤞

Ok it’s too late for me to get on my pc now but I’ll check them out tommorow thanks anyways!

**Comment by Emperorpacify** [comment]
> e

OK I have downloaded the mod and it works perfectly fine tysm!

**Comment by EwyBoy** [comment]
Awesome! Enjoy
