### ISSUE TITLE
FPS isn't showing up in-game or in top of the window

### ISSUE THREAD

**Issue by dragon3025** [EwyBoy/FPS-Monitor#6]
Maybe this relates to https://github.com/EwyBoy/FPS-Monitor/issues/4#issue-1167769394, but the FPS isn't showing up in-game or in the top of the window. I don't know if there's a hotkey for it and I don't see anything for in the controls menu, so I don't know how to make it show up.

**Comment by EwyBoy** [comment]
Mind filling out some extra information for me so I can easier debug this issue?

###### **Minecraft Version**
> Type here

###### Modloader Fabric / Forge
> Type here

###### **Modloader Version**
> Type here

###### **Mod Version**
> Type here

**Comment by dragon3025** [comment]
###### **Minecraft Version**
> 1.18.2

###### Modloader Fabric / Forge
> Fabric 0.13.3-1.18.2

###### **Mod Version**
> FPS-Monitor-1.18.2-1.1.0

**Comment by EwyBoy** [comment]
Hmm works just fine when installed using the Curse App 🤔

**Comment by TheBudgetMan** [comment]
When installed manually, it does not work for me either. Same configuration as OP.

**Comment by EwyBoy** [comment]
Could you try install Cloth Config and see if that might fix it, and report back to me if that solves it or not?
https://www.curseforge.com/minecraft/mc-mods/cloth-config

**Comment by TheBudgetMan** [comment]
Nevermind, it was the Forge edition. Sorry, my bad. New to modding.

**Comment by EwyBoy** [comment]
![image](https://user-images.githubusercontent.com/5883716/161605689-97a0fb2a-c04c-4c6a-a124-022864ba8c2a.png)
Released 6 new builds that should potentially fix all this 🤞🤞

**Comment by EwyBoy** [comment]
https://www.curseforge.com/minecraft/mc-mods/fps-monitor/files
